apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8-env
  labels:
    app: k8-env
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8-env
subjects:
- kind: ServiceAccount
  name: k8-env
  namespace: k8-env