apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-env
  labels:
    app: k8-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-env
  template:
    metadata:
      labels:
        app: k8-env
    spec:
      serviceAccountName: k8-env
      containers:
        - name: k8-env
          image: k8-env
          imagePullPolicy: Always
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/usr/bin/prestop.sh"]
          volumeMounts:
          - name: webhook-config
            mountPath: /etc/webhook/config
      volumes:
      - name: webhook-config
        configMap:
          name: k8-env
